In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

data = pd.read_csv('petrol_consumption.csv')
print(data)

    Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.00            3571            1976                         0.525   
1         9.00            4092            1250                         0.572   
2         9.00            3865            1586                         0.580   
3         7.50            4870            2351                         0.529   
4         8.00            4399             431                         0.544   
5        10.00            5342            1333                         0.571   
6         8.00            5319           11868                         0.451   
7         8.00            5126            2138                         0.553   
8         8.00            4447            8577                         0.529   
9         7.00            4512            8507                         0.552   
10        8.00            4391            5939                         0.530   
11        7.50            5126          

In [2]:
X = data.iloc[:, [0, 1, 2, 3]]
y = data['Petrol_Consumption']

X_array = np.array(X)
y_array = np.array(y)

print(X.columns)
print(X_array, type(X_array))

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)'],
      dtype='object')
[[9.0000e+00 3.5710e+03 1.9760e+03 5.2500e-01]
 [9.0000e+00 4.0920e+03 1.2500e+03 5.7200e-01]
 [9.0000e+00 3.8650e+03 1.5860e+03 5.8000e-01]
 [7.5000e+00 4.8700e+03 2.3510e+03 5.2900e-01]
 [8.0000e+00 4.3990e+03 4.3100e+02 5.4400e-01]
 [1.0000e+01 5.3420e+03 1.3330e+03 5.7100e-01]
 [8.0000e+00 5.3190e+03 1.1868e+04 4.5100e-01]
 [8.0000e+00 5.1260e+03 2.1380e+03 5.5300e-01]
 [8.0000e+00 4.4470e+03 8.5770e+03 5.2900e-01]
 [7.0000e+00 4.5120e+03 8.5070e+03 5.5200e-01]
 [8.0000e+00 4.3910e+03 5.9390e+03 5.3000e-01]
 [7.5000e+00 5.1260e+03 1.4186e+04 5.2500e-01]
 [7.0000e+00 4.8170e+03 6.9300e+03 5.7400e-01]
 [7.0000e+00 4.2070e+03 6.5800e+03 5.4500e-01]
 [7.0000e+00 4.3320e+03 8.1590e+03 6.0800e-01]
 [7.0000e+00 4.3180e+03 1.0340e+04 5.8600e-01]
 [7.0000e+00 4.2060e+03 8.5080e+03 5.7200e-01]
 [7.0000e+00 3.7180e+03 4.7250e+03 5.4000e-01]
 [7.0000e+00 4.7160e+03 5.9150e+03 

In [3]:
lin_reg = LinearRegression()
lin_reg.fit(X_array, y_array)

print(f"intercept: {lin_reg.intercept_}")
print(f"coefficients: {lin_reg.coef_}", type(lin_reg.coef_))
print(f'\nPetrol_Consumption = Petrol_tax*({lin_reg.coef_[0]:.2f}) + Average_income*({lin_reg.coef_[1]:.2f}) + Paved_Highways*({lin_reg.coef_[2]:.2f}) + Population_Driver_licence(%)*({lin_reg.coef_[3]:.2f}) + {lin_reg.intercept_:.2f}')

intercept: 377.2911464736752
coefficients: [-3.47901492e+01 -6.65887518e-02 -2.42588889e-03  1.33644936e+03] <class 'numpy.ndarray'>

Petrol_Consumption = Petrol_tax*(-34.79) + Average_income*(-0.07) + Paved_Highways*(-0.00) + Population_Driver_licence(%)*(1336.45) + 377.29


In [5]:
r_sq = lin_reg.score(X, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.6786867115698207


C:\Users\MyWork\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [6]:
y_pred = lin_reg.predict(X_array)

from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_array, y_pred)
mse = mean_squared_error(y_array, y_pred)
rmse = np.sqrt(mse)

print(f'\nmean_absolute_error = {mae:.2f}')
print(f'mean_squared_error = {mse:.2f}')
print(f'root mean_squared_error = {rmse:.2f}')


mean_absolute_error = 48.78
mean_squared_error = 3938.54
root mean_squared_error = 62.76
